apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: rook
spec:
  repositories:
  - name: rook
    url: 'https://charts.rook.io/release'
  releases:
  - name: rook-ceph
    chart: rook/rook-ceph
    version: 1.0.0
    namespace: rook-ceph
    values:
      manifests:
        network_policy: false
      # kubespray default volume path is set to /var/lib/kubelet/volume-plugins
      # this change is needed if we using kubernetes deployed by kubespray (KaaS)
      agent:
        flexVolumeDirPath: '/var/lib/kubelet/volume-plugins'
