apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-glance
spec:
  repositories:
  - name: oscore
    url: 'https://artifactory.mcp.mirantis.net/artifactory/helm-dev-virtual/'
  releases:
  - name: openstack-glance
    chart: oscore/glance
    version: 0.1.0
    namespace: default
    values:
      pod:
        replicas:
          api: 1
          registry: 1
      storage: rbd
      conf:
        glance:
          DEFAULT:
            enable_v1_api: True
            enable_v2_registry: True
          glance_store:
            rbd_store_crush_rule: replicated_ruleset
      volume:
        class_name: rook-ceph-block
        size: 2Gi
      
      ceph_client:
        configmap: rook-ceph-config
        user_secret_name: rook-ceph-admin-keyring
      images:
        tags:
          bootstrap: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          test: docker.io/xrally/xrally-openstack:1.3.0
          db_init: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          glance_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190529161356
          db_drop: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          ks_user: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          rabbit_init: docker.io/rabbitmq:3.7-management
          glance_fernet_setup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190529161356
          glance_fernet_rotate: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190529161356
          glance_credential_setup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190529161356
          glance_credential_rotate: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190529161356
          glance_credential_cleanup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          glance_api: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190529161356
          glance_domain_manage: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190529161356
          dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
          image_repo_sync: docker.io/docker:17.07.0
      manifests:
        network_policy: false
