apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: sample-cluster
spec:
  repositories:
  - name: oscore
    url: 'https://artifactory.mcp.mirantis.net/artifactory/helm-dev-virtual/'
  releases:
  - name: ingress-openstack-test1
    chart: oscore/ingress
    version: 0.1.0
    namespace: default
    values:
      manifests:
        network_policy: false
  - name: openstack-mariadb
    chart: oscore/mariadb
    version: 0.1.0
    namespace: default
    values:
      manifests:
        network_policy: false
  - name: openstack-rabbitmq-1
    chart: oscore/rabbitmq
    version: 0.1.0
    namespace: default
    values:
      pod:
        replicas:
          server: 1
      manifests:
        network_policy: false
  - name: openstack-memcached
    chart: oscore/memcached
    version: 0.1.0
    namespace: default
    values:
      manifests:
        network_policy: false
  - name: openstack-keystone
    chart: oscore/keystone
    version: 0.1.0
    namespace: default
    values:
      images:
        tags:
          bootstrap: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-xenial-20190517123131
          test: docker.io/xrally/xrally-openstack:1.3.0
          db_init: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-xenial-20190517123131
          keystone_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-xenial-20190517123131
          db_drop: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-xenial-20190517123131
          ks_user: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-xenial-20190517123131
          rabbit_init: docker.io/rabbitmq:3.7-management
          keystone_fernet_setup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-xenial-20190517123131
          keystone_fernet_rotate: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-xenial-20190517123131
          keystone_credential_setup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-xenial-20190517123131
          keystone_credential_rotate: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-xenial-20190517123131
          keystone_credential_cleanup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-xenial-20190517123131
          keystone_api: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-xenial-20190517123131
          keystone_domain_manage: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-xenial-20190517123131
          dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
          image_repo_sync: docker.io/docker:17.07.0
      manifests:
        network_policy: false
  - name: openstack-horizon
    chart: oscore/horizon
    version: 0.1.0
    namespace: default
    values:
      manifests:
        network_policy: false
