apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-network
spec:
  repositories:
  - name: oscore
    url: 'https://artifactory.mcp.mirantis.net/artifactory/helm-dev-virtual/'
  releases:
  - name: openstack-openvswitch
    chart: oscore/openvswitch
    version: 0.1.0
    namespace: default
    values:
      images:
        tags:
          openvswitch_db_server: docker.io/openstackhelm/openvswitch:latest-debian
          openvswitch_vswitchd: docker.io/openstackhelm/openvswitch:latest-debian
  - name: openstack-neutron
    chart: oscore/neutron
    version: 0.1.0
    namespace: default
    values:
      images:
        tags:
          bootstrap: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          test: docker.io/xrally/xrally-openstack:1.3.0
          db_init: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          neutron_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190529161356
          db_drop: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          rabbit_init: docker.io/rabbitmq:3.7-management
          ks_user: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          ks_service: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          ks_endpoints: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190529161356
          neutron_server: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190529161356
          neutron_dhcp: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190529161356
          neutron_metadata: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190529161356
          neutron_l3: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190529161356
          neutron_openvswitch_agent: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190529161356
          neutron_linuxbridge_agent: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190529161356
          neutron_sriov_agent: docker.io/openstackhelm/neutron:ocata-18.04-sriov
          neutron_sriov_agent_init: docker.io/openstackhelm/neutron:ocata-18.04-sriov
          dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
          image_repo_sync: docker.io/docker:17.07.0
      network:
        interface:
          tunnel: ens3
      conf:
        paste:
          app:neutronversions:
            paste.app_factory: neutron.pecan_wsgi.app:versions_factory
        neutron:
          DEFAULT:
            l3_ha: False
            max_l3_agents_per_router: 1
            l3_ha_network_type: vxlan
            dhcp_agents_per_network: 1
        plugins:
          ml2_conf:
            ml2_type_flat:
              flat_networks: public
          openvswitch_agent:
            agent:
              tunnel_types: vxlan
            ovs:
              bridge_mappings: public:br-ex
          linuxbridge_agent:
            linux_bridge:
              bridge_mappings: public:br-ex
